### ISSUE TITLE
Can't log into account to deploy

### ISSUE THREAD

**Issue by TonySpegel** [angular-schule/angular-cli-ghpages#112]
Hi there,

first of all: great package, thanks for your work!
As of yesterday or so I can't seem to be able to log into my account via cli, 
which is odd as this has worked for quite a while now. 
I tried logging in and after that using a incorrect password: 
![Screenshot_20200720_212136](https://user-images.githubusercontent.com/1145514/87977434-04746780-cacf-11ea-89de-99f088267f5d.png)

So basically it doesn't to anything after trying to log in.
Any ideas what this could be the cause? Anything I could provide to help?

**Comment by JohannesHoppe** [comment]
Does it work manually?

**Comment by TonySpegel** [comment]
I tried it like this, which also doesn't work
```Bash
ng deploy --repo=https://github.com/TonySpegel/catDetector.git --name="TonySpegel" --email=tonyspegel@googlemail.com --base-href="/catDetector/"
```
What's up with the `username@github.com` is that a default mail or something? Besides that: I can just push as usual into my repo

**Comment by JohannesHoppe** [comment]
I mean, can you do a `git pull` without the `ng deplo` wrapper

**Comment by TonySpegel** [comment]
this works just fine

**Comment by JohannesHoppe** [comment]
Basically, angular-cli-ghpages does not do any authentication stuff. It just clones a separate git repo and uses the remote from the current directory. If you do "git clone xxx" you should see the same error message. The best option would be to solve the login problem so that "git clone" works fine again.

Other possible solution:
1. Hacking user-name + password into the URL (really bad)
2. using the GH_TOKEN environment variable (acceptable)

**Comment by TonySpegel** [comment]
Hm `git clone` just works fine just like everything else related to git. Very weird
