### ISSUE TITLE
Routing / href issue

### ISSUE THREAD

**Issue by AndrewVetovitz** [angular-schule/angular-cli-ghpages#32]
I apologize if this is not the correct place to post this.

I keep getting this error in my web console. I was able to remove my routing and everything still worked luckily since I have a one page scrolling application, but how does one solve this issue otherwise. I have tried stack overflow searches, ect... for about an hour with little to help me.
http://andrewvetovitz.com is my web domain.
https://andrewvetovitz.github.io/andrewvetovitz.github.io-personal-website/ is the github / repository domain.

ERROR Error: Uncaught (in promise): SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://andrewvetovitz.github.io/andrewvetovitz.github.io-personal-website/' cannot be created in a document with origin 'http://andrewvetovitz.com' and URL 'http://andrewvetovitz.com/'.
Error: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://andrewvetovitz.github.io/andrewvetovitz.github.io-personal-website/' cannot be created in a document with origin 'http://andrewvetovitz.com' and URL 'http://andrewvetovitz.com/'.
    at BrowserPlatformLocation.webpackJsonp.../../../platform-browser/esm5/platform-browser.js.BrowserPlatformLocation.replaceState (platform-browser.js:1770)
    at

**Comment by JohannesHoppe** [comment]
Yes, this is not really the correct place! 😉

The error message says everything: GitHub.io and and your .com do not match. Use --baseHref during compiling to match both.

**Comment by AndrewVetovitz** [comment]
I think I've been programming too long today. Thanks!

**Comment by strucdaily** [comment]
Hi @AndrewVetovitz  Are you able to solve this ? I have been facing this problem as well, how do you configure the basehref to match both of them ?

**Comment by JohannesHoppe** [comment]
Please decide:
* users should see `mydomain.com` --> no need for `--baseHref`
* users should see `https://username.github.io/mydomain-repo/` --> setup `--baseHref`

### Let's go for the first example:

Assumption: you have an org-account. For personal accounts you have to adjust the example a bit.
First of all, you need a correct DNS record (A-record with IP for domains without subdomain, or CNAME-record for subdomains)
example:

<img width="958" alt="screen shot 2018-05-31 at 16 39 35" src="https://user-images.githubusercontent.com/640639/40788842-44c56eec-64f1-11e8-8ea1-dbeb50ab998a.png">

for this example I execute the following:

```bash
echo "book-monkey2.angular-buch.com" > dist/CNAME;
ngh --repo="https://GH_TOKEN@github.com/book-monkey2-build/SECOND_REPO.git"
```

GH_TOKEN must be kept secret. Setup an environment variable for this, so that it's not visible in the logs.
Why a second repo? I don't pollute the original repo with my build artifacts. This is up to you, you can also keep both in the same repo.

Cheers!
