### ISSUE TITLE
Angular 6 routing broken with custom domain

### ISSUE THREAD

**Issue by RockGuitarist1** [angular-schule/angular-cli-ghpages#40]
I pushed my project up to my repo using angular-cli-ghpages back when my project was still a github.io project and the website worked fine, but as soon as I added the CNAME to the dist folder and added the IPs to Google Domains, I went to access the site, the site comes up, but only the nav and footer. The routing is also broken.

I am not sure why adding a custom domain would break the website. Any ideas?

Here is the repo: https://github.com/RockGuitarist1/WaypointYouthCommunityCenter
Here is the website: http://waypointcommunitycenter.org/

**Comment by fmalcher** [comment]
You put in `https://rockguitarist1.github.io/WaypointYouthCommunityCenter/` as the base href, but `http://waypointcommunitycenter.org/` is the domain the web page is served under.
You need to provide the correct base href for your domain then:
```
ng build --prod --base-href=http://waypointcommunitycenter.org/
```

The error message on your page might also be related to this:
```
SyntaxError: export declarations may only appear at top level of a module
```

Another thing, but just as an info: You might want to install the FullCalendar package via npm: https://www.npmjs.com/package/fullcalendar
You can then include the script in your `angular.json` file instead of using a `<script>` tag in your `index.html`.

I'm closing this issue for now because it is not actually related to this project itself. 🙂

**Comment by RockGuitarist1** [comment]
Thanks for pointing out the script. I just had to remove the gcal one from index.html since I was importing it anyways inside of a ts file. I am however having an issue running the ngh command now using the new --base-href script. This is what I get back when running no-silent.

```Cloning https://github.com/RockGuitarist1/WaypointYouthCommunityCenter.git into ..\..\AppData\Roaming\npm\node_modules\angular-cli-ghpages\node_modules\gh-pages\.cache```

...

`Pushing`

```bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument```

**Comment by JohannesHoppe** [comment]
This is the most common issue. Please refer to this: https://github.com/angular-schule/angular-cli-ghpages/issues/14 or https://github.com/angular-schule/angular-cli-ghpages/issues/26. The easiest way is to get used to  GH_TOKENs (see readme)

TODO to myself: override the normal error message with a better help. 😉

**Comment by RockGuitarist1** [comment]
WOO, that did it. I used the one referenced in the Readme and included the name and email tags as well. Maybe in the readme note which access token is required. I just gave mine the Repo role.

**Comment by adesheddie** [comment]
hey @RockGuitarist1 , I see you fixed our issue, I am having the same. Please tell me how did you fix it ?
