### ISSUE TITLE
Facing issue for deployment with Angular6

### ISSUE THREAD

**Issue by sahilkatia** [angular-schule/angular-cli-ghpages#45]
```
 npm install -g angular-cli-ghpages
$ ng build --prod --base-href https://sahilkatia.github.io/resume/

ngh --dir dist/resume
```

Even then I am facing error

below is the screen
![capture](https://user-images.githubusercontent.com/14021901/45924619-aaa2b680-bed2-11e8-9af2-6d6631ecd7b1.PNG)

**Comment by fmalcher** [comment]
This has nothing to do with this project or with Angular itself.
See this comment for further info: https://github.com/angular-schule/angular-cli-ghpages/issues/37#issuecomment-391644410

You need to set the `base-href` just as a folder path, not with the complete URL.

```bash
ng build --prod --base-href=/resume/
```

**Comment by sahilkatia** [comment]
I am still facing same issue. Although its running perfect on my local
![capture](https://user-images.githubusercontent.com/14021901/45988358-87981400-c044-11e8-8e4d-ee0a6c665b4b.PNG)

**Comment by fmalcher** [comment]
Please take a look at your `index.html` inside your dist directory. You will find the base href at the top.
At the moment it's set to this which is definitely invalid 😉

<img width="590" alt="screen shot 2018-09-25 at 08 38 36" src="https://user-images.githubusercontent.com/1683147/45997018-914e6580-c09e-11e8-91a9-a3818f726340.png">

**Comment by suga0828** [comment]
I have a similar problem. I have already uploaded my files and the page is displayed well except for one image. The path of the image is different from the path where the image is saved.

Naturally I get a 404 error:
menu.png: 1 GET https://suga0828.github.io/assets/images/menu.png 404

The image is saved in the route:
https://suga0828.github.io/suga0828/assets/images/menu.png

When I inspect the image I observe the route:

src = "../ assets / images / menu.png"

which is the same as I have in my code but it will only work with:

src = "./ assets / images / menu.png"

I know that the problem is the path that has the img tag, not the path where the image is saved but I can not solve the problem.
