### ISSUE TITLE
Angular Next updates Core to Angular 9

### ISSUE THREAD

**Issue by Narshe1412** [angular-schule/angular-cli-ghpages#63]
Hello nice people

I'm trying to create my gh-pages branch but I keep getting 404s. I read in a previous closed issue #54 that I need to have my angular cli up to date. By the readme instructions the command is 
```ng update @angular/cli @angular/core --next=true```
However by running this I update my angular project to version 9. Is there a safer version I can use to keep my project in Angular 8 and still be able to publish without 404s?

Command output:
```
    Updating package.json with dependency @angular/cli @ "8.3.0-next.0" (was "8.0.6")...
    Updating package.json with dependency @angular/core @ "9.0.0-next.0" (was "8.0.3")...
```

My gh-pages repo using angular cli 8.0.6:
https://github.com/Narshe1412/Code-Institute-User-Centric-Algorithms/tree/gh-pages

Thanks for your help

**Comment by JohannesHoppe** [comment]
Thanks for pointing this out!  👍 
Indeed, the `next` tag points to different versions now – that's impractical.
In the past both pointed to 8.x.

```sh
npm info @angular/cli@next --> next: 8.3.0-next.1 (that's fine)
npm info @angular/core@next --> next: 9.0.0-next.1 (that's too much and not tested by me)
```

What we need is a version of the cli 8.3.0-next.0 or higher.
I would also update Angular, because I haven't tested this with an older version of Angular.
Please try the following:

```sh
ng update @angular/cli@8.3.0-next.1 @angular/core@8.2.1
# which (right now) the same as:
ng update @angular/cli@next @angular/core@latest
```

So we keep Angular inversion 8.x 
@Narshe1412 Please confirm that it worked for you!

**Comment by Narshe1412** [comment]
It works fine without the need to upgrade to core9. Thanks for the swift response.

Now I need to fix the HREF issues. I believe there's a bug related or a problem with my config. I'll open a new Issue if I can 100% reproduce it.

Thanks again!
