### ISSUE TITLE
Show loading-indicator while Project is uploading

### ISSUE THREAD

**Issue by TonySpegel** [angular-schule/angular-cli-ghpages#78]
Pretty much the title,

I was wondering if my CLI was frozen or something but nope, it just may take a while to upload everything. And for this case it'd be neat to have a loading-indicator of some kind.
Otherwise it's just `ES5 bundle generation complete.` and then after quite some time:
`🚀 Successfully published via angular-cli-ghpages! Have a nice day!`
Somewhere in between these two would be nice :)

And thank you for your great work

**Comment by fmalcher** [comment]
Thanks for the suggestion! If we do so, it should have an opt-out via a "progress=false" or "no-progress" flag. Otherwise it would pollute CI logs.

**Comment by JohannesHoppe** [comment]
That's a nice idea. It would be difficulty to figure out the real progress, because the upload is done via git executable and we would need to grab somehow the output from there.

@TonySpegel Is it fine for you too if it just prints: `Uploading via git, please wait...``
@fmalcher Logs are already polluted because of the progress of the build. Out circle logs are very long because of that... 🙄

**Comment by fmalcher** [comment]
@JohannesHoppe There should be a `--no-progress` option in angular-cli-ghpages that forwards to the build process!

**Comment by TonySpegel** [comment]
@JohannesHoppe of course, that would be sufficient =)

**Comment by JohannesHoppe** [comment]
I added the text:
> 👨‍🚀 Uploading via git, please wait...

**Comment by TonySpegel** [comment]
Thank you for adding this feature :smile_cat: great job :)

**Comment by amoebacodes** [comment]
@TonySpegel May I ask about how long had you waited until it finished uploading via git? I'm stuck on this step and I want to get an idea before I force quit my CLI. Thank you so much!
