### ISSUE TITLE
Blank page showing in angular 8.0.3

### ISSUE THREAD

**Issue by debashismoharana** [angular-schule/angular-cli-ghpages#82]
The console says: "Successfully published via angular-cli-ghpages! Have a nice day!"
But when I open the URL "https://debashismoharana.github.io/ghpages/", it shows empty page.

Github Link: https://github.com/debashismoharana/ghpages

![Capture](https://user-images.githubusercontent.com/15375367/69007486-53786480-0964-11ea-8f13-03ceea48e294.PNG)

**Comment by fmalcher** [comment]
The applications doe not run in the root folder but in a sub folder (`ghpages`). You need t provide the base href so that the bundles will not be searched for in the root but in the sub folder as well. See here for information about this: https://github.com/angular-schule/angular-cli-ghpages#base-href

**Comment by HarshalPuri10** [comment]
still not fixed sir

**Comment by fmalcher** [comment]
@HarshalPuri10 This is probably not an issue with this library, see my comment before. If you think it is, then please provide some clear information about what you think is wrong.

**Comment by santoshgite** [comment]
Create a copy of index.html with 404.html at the same folder and it will work.
